#!/bin/sh
# chkconfig: 35 94 94
# description: Tripwire Agent
# processname: twdaemon
# pidfile: /var/run/twdaemon.pid
#
### BEGIN INIT INFO
# Provides:       twdaemon
# Required-Start:
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 6
# Description:    Tripwire Daemon
### END INIT INFO
